services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e-mail_analyzer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d e-mail_analyzer"]
      interval: 5s
      timeout: 5s
      retries: 10

  nest-app:
    build:
      context: ./email-analyzer
      dockerfile: Dockerfile
    image: email-analyzer:latest
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/e-mail_analyzer?schema=public
    restart: unless-stopped
    networks:
      - app-net
    depends_on:
      db:
        condition: service_healthy

networks:
  app-net:
    driver: bridge

volumes:
  pgdata: